# Generated by Django 5.2 on 2025-10-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0002_notification_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('payment_reminder', 'Payment Reminder'), ('meeting', 'Meeting'), ('payout', 'Payout'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
